# Generated by Django 6.0.2 on 2026-03-23 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chathistory_user_alter_message_chat_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(choices=[('gemini-2.5-pro', 'Gemini 2 5'), ('gemini-2.5-flash', 'Gemini 2 5 Flash')], default='gemini-2.5-flash')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
