# Generated by Django 6.0.2 on 2026-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='model_name',
            field=models.TextField(choices=[('gemini-2.5-pro', 'gemini-2.5-pro'), ('gemini-2.5-flash', 'gemini-2.5-flash'), ('gemini-2.5-flash-lite', 'gemini-2.5-flash-lite')], default='gemini-2.5-flash'),
        ),
    ]
