# Generated by Django 6.0.2 on 2026-03-23 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmodel_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatHistory',
            new_name='ChatSession',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_history',
            new_name='chat_session',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='provider_name',
            field=models.TextField(default='google'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='model_name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ChatModelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='chat.chatmodel')),
            ],
        ),
    ]
