# Generated by Django 6.0.2 on 2026-04-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_chathistory_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='used_model',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_model', to='chat.chatmodel'),
        ),
    ]
