# Generated by Django 6.0.2 on 2026-02-19 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='upload_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
