# Generated by Django 6.0.2 on 2026-02-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_uploadhistory_upload_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='file_path',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
