# Generated by Django 6.0.2 on 2026-03-19 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_remove_uploadhistory_file_path_uploadhistory_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='action',
            field=models.TextField(choices=[('UPLOAD', 'Upload'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='UPLOAD'),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='actionAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_history', to='instructor.subject'),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('subjects', models.ManyToManyField(db_table='Materials', related_name='uploads', to='instructor.subject')),
            ],
        ),
    ]
