# Generated by Django 6.0.2 on 2026-03-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_remove_uploadhistory_file_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructor',
            table='Instructor',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
        migrations.AlterModelTable(
            name='upload',
            table='Upload',
        ),
        migrations.AlterModelTable(
            name='uploadhistory',
            table='UploadHistory',
        ),
    ]
