# Generated by Django 6.0.2 on 2026-03-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_instructor_table_alter_subject_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='upload',
            table=None,
        ),
        migrations.AlterModelTable(
            name='uploadhistory',
            table=None,
        ),
    ]
