# Generated by Django 6.0.2 on 2026-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_alter_instructor_table_alter_subject_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='subjects',
            field=models.ManyToManyField(db_table='instructor_materials', related_name='uploads', to='instructor.subject'),
        ),
    ]
