# Generated by Django 6.0.2 on 2026-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_alter_upload_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='subjects',
            field=models.ManyToManyField(related_name='uploads', to='instructor.subject'),
        ),
    ]
