# Generated by Django 6.0.2 on 2026-03-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_alter_upload_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='subject',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_history', to='instructor.upload'),
        ),
    ]
