# Generated by Django 6.0.2 on 2026-04-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_remove_uploadhistory_subject_uploadhistory_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
