# Generated by Django 6.0.2 on 2026-03-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
