# Generated by Django 6.0.2 on 2026-04-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_email_and_more'),
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
    ]
